# frozen_string_literal: true

source "https://rubygems.org"

gem "rubocop", require: false # https://github.com/rubocop/rubocop
# gem "rubyXL" # https://github.com/weshatheleopard/rubyXL
gem "pry"
gem "roo" # https://github.com/roo-rb/roo
