# require "rubyXL"
# require "rubyXL/convenience_methods"
# require "rubyXL/convenience_methods/cell"
# require "rubyXL/convenience_methods/color"
# require "rubyXL/convenience_methods/font"
# require "rubyXL/convenience_methods/workbook"
# require "rubyXL/convenience_methods/worksheet"

require "roo"
require "csv"
require "pry"
